services:
    web:
      ports: !reset []
      expose:
        - "8000"
      restart: unless-stopped
      networks:
        - default
        - ai_analytics_shared

networks:
  ai_analytics_shared:
    external: true
    name: ai-analytics_ai-analytics
